name: example
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  qimendunjia:
    git:
      url: http://xuan:***@192.168.0.165:3000/xuan/xuan-qimendunjia.git
      ref: main
  xuan_common:
    git:
      url: http://xuan:***@192.168.0.165:3000/xuan/xuan-common.git
      ref: main
  provider: ^6.1.1
  ai_core:
    git:
      url: http://xuan:***@192.168.0.165:3000/xuan/xuan-ai.git
      ref: main
  flutter_ai_toolkit: ^0.9.1
  logging: ^1.2.0
  timezone: ^0.11.0

  lottie: ^3.3.2
  cupertino_icons: ^1.0.8

dependency_overrides:
  google_fonts: ^8.0.0
  xuan_common:
    path: ../../xuan-common
  four_zhu_card:
    path: ../../xuan-four-zhu-card
  four_zhu_host:
    path: ../../xuan-four-zhu-host
  four_zhu_templates:
    path: ../../xuan-four-zhu-templates
  qimendunjia:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/qi_men_dun_jia/
    - assets/lotties/
    - assets/backgrounds/
    - assets/dataset/
